name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x # Versão do Node.js compatível com o seu projeto

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Type check
        run: yarn type-check

      - name: Run tests
        run: yarn test
